apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-guardian
spec:
  template:
    spec:
      containers:
        - name: repo-guardian
          env:
            - name: DRY_RUN
              value: "true"
            - name: LOG_LEVEL
              value: debug
            - name: SCHEDULE_INTERVAL
              value: 24h
