apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-tools

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - serviceaccount.yaml

labels:
  - pairs:
      app.kubernetes.io/name: repo-guardian
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
