apiVersion: v1
kind: Service
metadata:
  name: repo-guardian
  labels:
    app: repo-guardian
spec:
  selector:
    app: repo-guardian
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
